import { Metadata } from 'next';
/** @jsxRuntime classic */
/** @jsx jsx */

import { css } from '@emotion/react';
import type { NextPage } from 'next';
import Terminal from '../common/components/terminal';
export const metadata: Metadata = {
  title: `David Kim`,
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
};

const Home: NextPage = () => {
  const gradientBackground = css({
    width: '100%',
    height: '100vh',
    background:
      'conic-gradient(from 217.29deg at 51.63% 52.16%,#2400ff 0deg,#0087ff 19.5deg,#ff1d7a 102.75deg,#f5381b 152.25deg,#ff5335 208.88deg,#691eff 291deg)',
    padding: '100px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center'
    //backgroundImage: 'linear-gradient(to right, #ff8177 0%, #ff867a 0%, #ff8c7f 21%, #f99185 52%, #cf556c 78%, #b12a5b 100%)'
  });

  return (
    <div>
      <main css={gradientBackground}>
        <Terminal />
      </main>

      <footer>
        {/*  <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  );
};

export default Home;
